In [6]:
import numpy as np

X = np.array([[4, 2]]).reshape(2, 1)
Rinv = np.array([[1/16]])

Rinv = (2+1/2) * (Rinv - (Rinv * X @ X.T * Rinv) / (2 + X * Rinv @ X.T))
print("AutoCorr: \n", Rinv) 

X = np.array([[4, 2, 1]]).reshape(3, 1)
Rinv = np.append(Rinv, np.array([[0,0]]), axis=0)
Rinv = np.append(Rinv, np.array([[0],[0],[0]]), axis=1)

Rinv = (3+1/3) * (Rinv - (Rinv @ X @ X.T @ Rinv) / (2+ X.T @ Rinv @ X))
print("AutoCorr: \n", Rinv) 

AutoCorr: 
 [[0.10416667 0.125     ]
 [0.125      0.13888889]]
AutoCorr: 
 [[0.10912698 0.13888889 0.        ]
 [0.13888889 0.13888889 0.        ]
 [0.         0.         0.        ]]


In [47]:
#defining the dft matrix
import numpy as np
n = 8
F = np.zeros([n,n], dtype=complex)
for i in range(0, n):
    for k in range(0,n):
        F[i][k] = np.round(np.exp((2j*np.pi/n)*i*k), 3)

print(F)

[[ 1.   +0.j     1.   +0.j     1.   +0.j     1.   +0.j     1.   +0.j
   1.   +0.j     1.   +0.j     1.   +0.j   ]
 [ 1.   +0.j     0.707+0.707j  0.   +1.j    -0.707+0.707j -1.   +0.j
  -0.707-0.707j -0.   -1.j     0.707-0.707j]
 [ 1.   +0.j     0.   +1.j    -1.   +0.j    -0.   -1.j     1.   -0.j
   0.   +1.j    -1.   +0.j    -0.   -1.j   ]
 [ 1.   +0.j    -0.707+0.707j -0.   -1.j     0.707+0.707j -1.   +0.j
   0.707-0.707j  0.   +1.j    -0.707-0.707j]
 [ 1.   +0.j    -1.   +0.j     1.   -0.j    -1.   +0.j     1.   -0.j
  -1.   +0.j     1.   -0.j    -1.   +0.j   ]
 [ 1.   +0.j    -0.707-0.707j  0.   +1.j     0.707-0.707j -1.   +0.j
   0.707+0.707j -0.   -1.j    -0.707+0.707j]
 [ 1.   +0.j    -0.   -1.j    -1.   +0.j     0.   +1.j     1.   -0.j
  -0.   -1.j    -1.   +0.j    -0.   +1.j   ]
 [ 1.   +0.j     0.707-0.707j -0.   -1.j    -0.707-0.707j -1.   +0.j
  -0.707+0.707j -0.   +1.j     0.707+0.707j]]


In [31]:
import numpy as np
#creating the input matrix

# Define the first column
first_col = np.array([14, 13, 12, 11, 7, 3, 2, 1])

# Create the circulant Toeplitz matrix
n = len(first_col)
C = np.zeros((n, n), dtype=int)

for i in range(n):
    C[i, :] = np.roll(first_col, i)

print(C.T)


[[14  1  2  3  7 11 12 13]
 [13 14  1  2  3  7 11 12]
 [12 13 14  1  2  3  7 11]
 [11 12 13 14  1  2  3  7]
 [ 7 11 12 13 14  1  2  3]
 [ 3  7 11 12 13 14  1  2]
 [ 2  3  7 11 12 13 14  1]
 [ 1  2  3  7 11 12 13 14]]


In [40]:
eig_vals, eig_vects = np.linalg.eig(C)
eig_vals

array([63. +0.j        ,  7.+24.14213562j,  7.-24.14213562j,
        7. +0.j        ,  7. +4.14213562j,  7. -4.14213562j,
        7. +4.j        ,  7. -4.j        ])

In [37]:
eigen_vals = np.diag(np.linalg.inv(F) @ C @ F) #@ is the matrix multiplier in python
eigen_vals

array([63.-2.18575158e-15j,  7.+2.41421358e+01j,  7.+4.00000000e+00j,
        7.+4.14213579e+00j,  7.-2.42861287e-16j,  7.-4.14213579e+00j,
        7.-4.00000000e+00j,  7.-2.41421358e+01j])

In [45]:
np.fft.fft(C[0,:])

array([63. +0.j        ,  7.-24.14213562j,  7. -4.j        ,
        7. -4.14213562j,  7. +0.j        ,  7. +4.14213562j,
        7. +4.j        ,  7.+24.14213562j])